// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.31.1
// source: greeter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGreeterSvcListGreeter = "/im_server.GreeterSvc/ListGreeter"

type GreeterSvcHTTPServer interface {
	// ListGreeter Sends a greeting
	ListGreeter(context.Context, *ListGreeterReq) (*ListGreeterRsp, error)
}

func RegisterGreeterSvcHTTPServer(s *http.Server, srv GreeterSvcHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/greeter/list", _GreeterSvc_ListGreeter0_HTTP_Handler(srv))
}

func _GreeterSvc_ListGreeter0_HTTP_Handler(srv GreeterSvcHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGreeterReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterSvcListGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGreeter(ctx, req.(*ListGreeterReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGreeterRsp)
		return ctx.Result(200, reply)
	}
}

type GreeterSvcHTTPClient interface {
	ListGreeter(ctx context.Context, req *ListGreeterReq, opts ...http.CallOption) (rsp *ListGreeterRsp, err error)
}

type GreeterSvcHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterSvcHTTPClient(client *http.Client) GreeterSvcHTTPClient {
	return &GreeterSvcHTTPClientImpl{client}
}

func (c *GreeterSvcHTTPClientImpl) ListGreeter(ctx context.Context, in *ListGreeterReq, opts ...http.CallOption) (*ListGreeterRsp, error) {
	var out ListGreeterRsp
	pattern := "/v1/greeter/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGreeterSvcListGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
