// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: greeter.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GreeterSvc_ListGreeter_FullMethodName = "/im_server.GreeterSvc/ListGreeter"
)

// GreeterSvcClient is the client API for GreeterSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type GreeterSvcClient interface {
	// Sends a greeting
	ListGreeter(ctx context.Context, in *ListGreeterReq, opts ...grpc.CallOption) (*ListGreeterRsp, error)
}

type greeterSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterSvcClient(cc grpc.ClientConnInterface) GreeterSvcClient {
	return &greeterSvcClient{cc}
}

func (c *greeterSvcClient) ListGreeter(ctx context.Context, in *ListGreeterReq, opts ...grpc.CallOption) (*ListGreeterRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGreeterRsp)
	err := c.cc.Invoke(ctx, GreeterSvc_ListGreeter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterSvcServer is the server API for GreeterSvc service.
// All implementations must embed UnimplementedGreeterSvcServer
// for forward compatibility.
//
// The greeting service definition.
type GreeterSvcServer interface {
	// Sends a greeting
	ListGreeter(context.Context, *ListGreeterReq) (*ListGreeterRsp, error)
	mustEmbedUnimplementedGreeterSvcServer()
}

// UnimplementedGreeterSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGreeterSvcServer struct{}

func (UnimplementedGreeterSvcServer) ListGreeter(context.Context, *ListGreeterReq) (*ListGreeterRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGreeter not implemented")
}
func (UnimplementedGreeterSvcServer) mustEmbedUnimplementedGreeterSvcServer() {}
func (UnimplementedGreeterSvcServer) testEmbeddedByValue()                    {}

// UnsafeGreeterSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterSvcServer will
// result in compilation errors.
type UnsafeGreeterSvcServer interface {
	mustEmbedUnimplementedGreeterSvcServer()
}

func RegisterGreeterSvcServer(s grpc.ServiceRegistrar, srv GreeterSvcServer) {
	// If the following call pancis, it indicates UnimplementedGreeterSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GreeterSvc_ServiceDesc, srv)
}

func _GreeterSvc_ListGreeter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGreeterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterSvcServer).ListGreeter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GreeterSvc_ListGreeter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterSvcServer).ListGreeter(ctx, req.(*ListGreeterReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GreeterSvc_ServiceDesc is the grpc.ServiceDesc for GreeterSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreeterSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im_server.GreeterSvc",
	HandlerType: (*GreeterSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGreeter",
			Handler:    _GreeterSvc_ListGreeter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}
