// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: init.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_init_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Config_Source         `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"` //配置源
	Zap           *Config_Zap            `protobuf:"bytes,2,opt,name=zap,proto3" json:"zap,omitempty"`       //日志配置
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_init_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetSource() *Config_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Config) GetZap() *Config_Zap {
	if x != nil {
		return x.Zap
	}
	return nil
}

type Config_Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apollo        *Config_Apollo         `protobuf:"bytes,1,opt,name=apollo,proto3" json:"apollo,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config_Source) Reset() {
	*x = Config_Source{}
	mi := &file_init_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Source) ProtoMessage() {}

func (x *Config_Source) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Source.ProtoReflect.Descriptor instead.
func (*Config_Source) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Config_Source) GetApollo() *Config_Apollo {
	if x != nil {
		return x.Apollo
	}
	return nil
}

func (x *Config_Source) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

type Config_Zap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`                                //日志文件路径
	Console       bool                   `protobuf:"varint,2,opt,name=console,proto3" json:"console,omitempty"`                         //是否输出到终端，用于命令行启动显示
	MaxAge        int32                  `protobuf:"varint,3,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`             //最大存放天数，0为长期保存
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`                              //等级，默认info级别，有debug、info、warn、error等
	MaxSize       int32                  `protobuf:"varint,5,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`          //文件最大大小，M为单位
	MaxBackups    int32                  `protobuf:"varint,6,opt,name=max_backups,json=maxBackups,proto3" json:"max_backups,omitempty"` //日志文件最大滚动数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config_Zap) Reset() {
	*x = Config_Zap{}
	mi := &file_init_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Zap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Zap) ProtoMessage() {}

func (x *Config_Zap) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Zap.ProtoReflect.Descriptor instead.
func (*Config_Zap) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Config_Zap) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Config_Zap) GetConsole() bool {
	if x != nil {
		return x.Console
	}
	return false
}

func (x *Config_Zap) GetMaxAge() int32 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Config_Zap) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Config_Zap) GetMaxSize() int32 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

func (x *Config_Zap) GetMaxBackups() int32 {
	if x != nil {
		return x.MaxBackups
	}
	return 0
}

type Config_Apollo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Cluster        string                 `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Endpoint       string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Namespace      string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	OriginalConfig bool                   `protobuf:"varint,5,opt,name=original_config,json=originalConfig,proto3" json:"original_config,omitempty"`
	EnableBackup   bool                   `protobuf:"varint,6,opt,name=enable_backup,json=enableBackup,proto3" json:"enable_backup,omitempty"`
	BackupPath     string                 `protobuf:"bytes,7,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	Secret         string                 `protobuf:"bytes,8,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config_Apollo) Reset() {
	*x = Config_Apollo{}
	mi := &file_init_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config_Apollo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Apollo) ProtoMessage() {}

func (x *Config_Apollo) ProtoReflect() protoreflect.Message {
	mi := &file_init_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Apollo.ProtoReflect.Descriptor instead.
func (*Config_Apollo) Descriptor() ([]byte, []int) {
	return file_init_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Config_Apollo) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Config_Apollo) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Config_Apollo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Config_Apollo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Config_Apollo) GetOriginalConfig() bool {
	if x != nil {
		return x.OriginalConfig
	}
	return false
}

func (x *Config_Apollo) GetEnableBackup() bool {
	if x != nil {
		return x.EnableBackup
	}
	return false
}

func (x *Config_Apollo) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *Config_Apollo) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_init_proto protoreflect.FileDescriptor

const file_init_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"init.proto\x12\x04conf\x1a\fserver.proto\x1a\n" +
	"data.proto\"Q\n" +
	"\tBootstrap\x12$\n" +
	"\x06server\x18\x01 \x01(\v2\f.conf.ServerR\x06server\x12\x1e\n" +
	"\x04data\x18\x02 \x01(\v2\n" +
	".conf.DataR\x04data\"\xc2\x04\n" +
	"\x06Config\x12+\n" +
	"\x06source\x18\x01 \x01(\v2\x13.conf.Config.SourceR\x06source\x12\"\n" +
	"\x03zap\x18\x02 \x01(\v2\x10.conf.Config.ZapR\x03zap\x1aI\n" +
	"\x06Source\x12+\n" +
	"\x06apollo\x18\x01 \x01(\v2\x13.conf.Config.ApolloR\x06apollo\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x1a\x9e\x01\n" +
	"\x03Zap\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file\x12\x18\n" +
	"\aconsole\x18\x02 \x01(\bR\aconsole\x12\x17\n" +
	"\amax_age\x18\x03 \x01(\x05R\x06maxAge\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x19\n" +
	"\bmax_size\x18\x05 \x01(\x05R\amaxSize\x12\x1f\n" +
	"\vmax_backups\x18\x06 \x01(\x05R\n" +
	"maxBackups\x1a\xfa\x01\n" +
	"\x06Apollo\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12'\n" +
	"\x0foriginal_config\x18\x05 \x01(\bR\x0eoriginalConfig\x12#\n" +
	"\renable_backup\x18\x06 \x01(\bR\fenableBackup\x12\x1f\n" +
	"\vbackup_path\x18\a \x01(\tR\n" +
	"backupPath\x12\x16\n" +
	"\x06secret\x18\b \x01(\tR\x06secretB\x1eZ\x1cim-server/internal/conf;confb\x06proto3"

var (
	file_init_proto_rawDescOnce sync.Once
	file_init_proto_rawDescData []byte
)

func file_init_proto_rawDescGZIP() []byte {
	file_init_proto_rawDescOnce.Do(func() {
		file_init_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_init_proto_rawDesc), len(file_init_proto_rawDesc)))
	})
	return file_init_proto_rawDescData
}

var file_init_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_init_proto_goTypes = []any{
	(*Bootstrap)(nil),     // 0: conf.Bootstrap
	(*Config)(nil),        // 1: conf.Config
	(*Config_Source)(nil), // 2: conf.Config.Source
	(*Config_Zap)(nil),    // 3: conf.Config.Zap
	(*Config_Apollo)(nil), // 4: conf.Config.Apollo
	(*Server)(nil),        // 5: conf.Server
	(*Data)(nil),          // 6: conf.Data
}
var file_init_proto_depIdxs = []int32{
	5, // 0: conf.Bootstrap.server:type_name -> conf.Server
	6, // 1: conf.Bootstrap.data:type_name -> conf.Data
	2, // 2: conf.Config.source:type_name -> conf.Config.Source
	3, // 3: conf.Config.zap:type_name -> conf.Config.Zap
	4, // 4: conf.Config.Source.apollo:type_name -> conf.Config.Apollo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_init_proto_init() }
func file_init_proto_init() {
	if File_init_proto != nil {
		return
	}
	file_server_proto_init()
	file_data_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_init_proto_rawDesc), len(file_init_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_init_proto_goTypes,
		DependencyIndexes: file_init_proto_depIdxs,
		MessageInfos:      file_init_proto_msgTypes,
	}.Build()
	File_init_proto = out.File
	file_init_proto_goTypes = nil
	file_init_proto_depIdxs = nil
}
