// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTGreeter = "t_greeter"

// TGreeter 问候者表
type TGreeter struct {
	ID        uint64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增ID" json:"id"`                      // 自增ID
	CreatedAt *time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	CreatedBy uint32     `gorm:"column:created_by;not null;comment:创建人" json:"created_by"`                            // 创建人
	UpdatedBy uint32     `gorm:"column:updated_by;not null;comment:更新人" json:"updated_by"`                            // 更新人
	Age       uint32     `gorm:"column:age;not null;comment:年龄" json:"age"`                                           // 年龄
	Name      string     `gorm:"column:name;not null;comment:姓名" json:"name"`                                         // 姓名
}

// TableName TGreeter's table name
func (*TGreeter) TableName() string {
	return TableNameTGreeter
}
